### ISSUE TITLE
communication with server: deleting not yet started job leaves the job on the server

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#9]
deleting job that is still queued ends with happy deleting on the client but the PBS has the job still scheduled....

**Comment by xulman** [comment]
okay... one must first "cancel" and only then "delete works".... WARN THEN AT LEAST!

**Comment by xulman** [comment]
deleting job is *NOT* deleting files on the server

**Comment by velissarious** [comment]
Yes, this is a bug with the delete context menu item not being disabled when the job is in a state other than running. It should also be disabled when queued etc. This bug was located in `hpc-workflow-manager-client`.

This has now been fixed. The fix will be included in the next release. 
Now, to delete a job the job must be done one way or another. The user can cancel the job to delete it earlier. 

Deleting jobs is not deleting files on the remote side on purpose as uploading huge data sets and deleting them with the job would be inefficient. Deletion is only local.
